apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j97jt5bq1-go
  janus-idp.io/tekton: j97jt5bq1-go
  backstage.io/kubernetes-id: j97jt5bq1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j97jt5bq1-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
